name: ShellCheck Linter Template

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:

    shellcheck-linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run ShellCheck
              uses: ragsworks/reusable-linters/.github/actions/shellcheck@master
              with:
                  cli-args: "--format=checkstyle --severity=info .github/actions/shellcheck/docker/tests/script.sh"
